# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robobuf/device_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brobobuf/device_status.proto\x12\x07robobuf\"c\n\x0c\x44\x65viceStatus\x12\x11\n\titeration\x18\x01 \x01(\x04\x12\x12\n\nsleepTimeS\x18\x02 \x01(\x04\x12\x13\n\x0b\x61\x63tiveTimeS\x18\x03 \x01(\x04\x12\x17\n\x0fsendFailedCount\x18\x04 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robobuf.device_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICESTATUS._serialized_start=40
  _DEVICESTATUS._serialized_end=139
# @@protoc_insertion_point(module_scope)
