# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robobuf/display_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1brobobuf/display_state.proto\x12\x07robobuf\"p\n\x0c\x44isplayState\x12\x18\n\x10\x62\x61\x63kground_color\x18\x01 \x01(\r\x12\x12\n\x05image\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\t\n\x01x\x18\x03 \x01(\r\x12\t\n\x01y\x18\x04 \x01(\r\x12\x12\n\nbrightness\x18\x05 \x01(\rB\x08\n\x06_imageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robobuf.display_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DISPLAYSTATE._serialized_start=40
  _DISPLAYSTATE._serialized_end=152
# @@protoc_insertion_point(module_scope)
