# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robobuf/led_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17robobuf/led_state.proto\x12\x07robobuf\"G\n\x08LedState\x12\x0e\n\x06global\x18\x01 \x01(\x08\x12\r\n\x05user1\x18\x02 \x01(\x08\x12\r\n\x05user2\x18\x03 \x01(\x08\x12\r\n\x05user3\x18\x04 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robobuf.led_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEDSTATE._serialized_start=36
  _LEDSTATE._serialized_end=107
# @@protoc_insertion_point(module_scope)
