# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robobuf/robot_to_gateway_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robobuf import display_state_pb2 as robobuf_dot_display__state__pb2
from robobuf import led_state_pb2 as robobuf_dot_led__state__pb2
from robobuf import stromzaehler_state_pb2 as robobuf_dot_stromzaehler__state__pb2
from robobuf import zisternensensor_state_pb2 as robobuf_dot_zisternensensor__state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&robobuf/robot_to_gateway_message.proto\x12\x07robobuf\x1a\x1brobobuf/display_state.proto\x1a\x17robobuf/led_state.proto\x1a robobuf/stromzaehler_state.proto\x1a#robobuf/zisternensensor_state.proto\"\xf4\x01\n\x15RobotToGatewayMessage\x12.\n\rdisplay_state\x18\x01 \x01(\x0b\x32\x15.robobuf.DisplayStateH\x00\x12&\n\tled_state\x18\x02 \x01(\x0b\x32\x11.robobuf.LedStateH\x00\x12\x38\n\x12stromzaehler_state\x18\x03 \x01(\x0b\x32\x1a.robobuf.StromzaehlerStateH\x00\x12>\n\x15zisternensensor_state\x18\x04 \x01(\x0b\x32\x1d.robobuf.ZisternensensorStateH\x00\x42\t\n\x07messageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robobuf.robot_to_gateway_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROBOTTOGATEWAYMESSAGE._serialized_start=177
  _ROBOTTOGATEWAYMESSAGE._serialized_end=421
# @@protoc_insertion_point(module_scope)
