# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robobuf/stromzaehler_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from robobuf import device_status_pb2 as robobuf_dot_device__status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n robobuf/stromzaehler_state.proto\x12\x07robobuf\x1a\x1brobobuf/device_status.proto\",\n\tPowerData\x12\r\n\x05sumWh\x18\x01 \x01(\x01\x12\x10\n\x08\x63urrentW\x18\x02 \x01(\x01\"5\n\x10StromzaehlerData\x12!\n\x05power\x18\x01 \x01(\x0b\x32\x12.robobuf.PowerData\",\n\x12StromzaehlerConfig\x12\x16\n\x0e\x63ontinuousMode\x18\x01 \x01(\x08\"\xbf\x01\n\x11StromzaehlerState\x12%\n\x06status\x18\x01 \x01(\x0b\x32\x15.robobuf.DeviceStatus\x12+\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x1b.robobuf.StromzaehlerConfig\x12+\n\x08haushalt\x18\x03 \x01(\x0b\x32\x19.robobuf.StromzaehlerData\x12)\n\x06waerme\x18\x04 \x01(\x0b\x32\x19.robobuf.StromzaehlerDatab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robobuf.stromzaehler_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POWERDATA._serialized_start=74
  _POWERDATA._serialized_end=118
  _STROMZAEHLERDATA._serialized_start=120
  _STROMZAEHLERDATA._serialized_end=173
  _STROMZAEHLERCONFIG._serialized_start=175
  _STROMZAEHLERCONFIG._serialized_end=219
  _STROMZAEHLERSTATE._serialized_start=222
  _STROMZAEHLERSTATE._serialized_end=413
# @@protoc_insertion_point(module_scope)
